# GitHub Actions
# https://help.github.com/en/articles/configuring-a-workflow
name: Unit tests

on: push

jobs:
  dependencies:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      # install a specific version of Node using
      # https://github.com/actions/setup-node
      - name: Use Node.js v18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # just so we learn about available environment variables GitHub provides
      - name: Print env variables
        run: |
          npm i -g @bahmutov/print-env
          print-env GITHUB

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list
        
      # Install dependencies
      - name: Dependencies
        run: npm install
  test_dialogic:
    runs-on: ubuntu-20.04
    needs: dependencies
    steps:
      - uses: actions/checkout@v3
      - name: Dialogic core
        working-directory: ./packages/test-dialogic
        run: npm run test
  test_dialogic_mithril:
    runs-on: ubuntu-20.04
    needs: dependencies
    steps:
      - uses: actions/checkout@v3
      - name: Mithril
        working-directory: packages/test-dialogic-mithril
        run: npm run test
  test_dialogic_react:
    runs-on: ubuntu-20.04
    needs: dependencies
    steps:
      - uses: actions/checkout@v3
      - name: React
        working-directory: packages/test-dialogic-react
        run: npm run test
  test_dialogic_svelte:
    runs-on: ubuntu-20.04
    needs: dependencies
    steps:
      - uses: actions/checkout@v3
      - name: Svelte
        working-directory: packages/test-dialogic-svelte
        run: npm run test

