# GitHub Actions
# https://help.github.com/en/articles/configuring-a-workflow
name: Unit tests

on: push

jobs:
  dependencies:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      # install a specific version of Node using
      # https://github.com/actions/setup-node
      - name: Use Node.js v18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # just so we learn about available environment variables GitHub provides
      - name: Print env variables
        run: |
          npm i -g @bahmutov/print-env
          print-env GITHUB

      # Install dependencies
      - name: Dependencies
        run: |
          npm install
  test_dialogic:
    runs-on: ubuntu-20.04
    needs: [dependencies]
    steps:
      - uses: actions/checkout@v3
      - run: |
        cd packages/test-dialogic
        npm run test
  test_dialogic_mithril:
    runs-on: ubuntu-20.04
    needs: [dependencies]
    steps:
      - uses: actions/checkout@v3
      - run: |
        cd packages/test-dialogic-mithril
        npm run test
  test_dialogic_react:
    runs-on: ubuntu-20.04
    needs: [dependencies]
    steps:
      - uses: actions/checkout@v3
      - run: |
        cd packages/test-dialogic-react
        npm run test
  test_dialogic_svelte:
    runs-on: ubuntu-20.04
    needs: [dependencies]
    steps:
      - uses: actions/checkout@v3
      - run: |
        cd packages/test-dialogic-svelte
        npm run test

